export const city_category =
   [
   
     
      {
        id:'5',
        title: 'BeautyParlour',
        img: 'assets\\icon\\category\\image (15).png',
        Link: '/catlist' ,
      },
      {
        id:'6',
        title: 'Decorators',
        img: 'assets\\icon\\category\\image (10).png',
        Link: '/catlist' ,
      },
      {
        id:'1',
        title: 'Doctors',
        img: 'assets\\icon\\category\\image (8).png',
        Link: '/doctor' ,
        color : 'black',
      },
   
      {
        id:'7',
        title: 'Private Bus/Bus on Hire',
        img: 'assets\\icon\\category\\image (4).png',
        Link: '/catlist' ,
      },
      {
        id:'8',
        title: 'Car on Rent',
        img: 'assets\\icon\\category\\image (28).png',
        Link: '/catlist' ,
      },
      {
        id:'9',
        title: 'Cake Shop(Bakery)',
        img: 'assets\\icon\\category\\image (2).png',
        Link: '/catlist' ,
      },
      {
        id:'10',
        title: 'Carpainters',
        img: 'assets\\icon\\category\\image (5).png',
        Link: '/catlist' ,
      },
      {
        id:'11',
        title: 'Caterings',
        img: 'assets\\icon\\category\\image (6).png',
        Link: '/catlist' ,
      },
      {
        id:'12',
        title: 'Civil Contractors',
        img: 'assets\\icon\\category\\image (9).png',
        Link: '/catlist' ,
      },
      {
        id:'13',
        title: 'Computer Repair',
        img: 'assets\\icon\\category\\image (27).png',
        Link: '/catlist' ,
      },
      {
        id:'14',
        title: 'Computer Training',
        img: 'assets\\icon\\category\\image (13).png',
        Link: '/catlist' ,
      },
      {
        id:'15',
        title: 'Educational Institute',
        img: 'assets\\icon\\category\\image (22).png',
        Link: '/catlist' ,
      },
      {
        id:'16',
        title: 'Electrician',
        img: 'assets\\icon\\category\\image (21).png',
        Link: '/catlist' ,
      },
      {
        id:'17',
        title: 'Groceries',
        img: 'assets\\icon\\category\\image (24).png',
        Link: '/catlist' ,
      },
      {
        id:'18',
        title: 'Gym',
        img: 'assets\\icon\\category\\image (26).png',
        Link: '/catlist' ,
      },
      {
        id:'19',
        title: 'Painter',
        img: 'assets\\icon\\category\\image (18).png',
        Link: '/catlist' ,
      },
      {
        id:'20',
        title: 'Salon',
        img: 'assets\\icon\\category\\image (23).png',
        Link: '/catlist' ,
      },
      {
        id:'21',
        title: 'Plumber',
        img: 'assets\\icon\\category\\image (21).png',
        Link: '/catlist' ,
      },
      {
        id:'22',
        title: 'Banks',
        img: 'assets\\icon\\category\\image (3).png',
        Link: '/catlist' ,
      },
      {
        id:'23',
        title: 'Internet Provider',
        img: 'assets\\icon\\category\\image (30).png',
        Link: '/catlist' ,
      },
      {
        id:'24',
        title: 'Home Decor',
        img: 'assets\\icon\\category\\image (7).png',
        Link: '/catlist' ,
      },
      {
        id:'25',
        title: 'Logistics/ Courier',
        img: 'assets\\icon\\category\\image (14).png',
        Link: '/catlist' ,
      },
      {
        id:'26',
        title: 'Movie Theater',
        img: 'assets\\icon\\category\\image (17).png',
        Link: '/catlist' ,
      },
      {
        id:'27',
        title: 'Milk Dairy',
        img: 'assets\\icon\\category\\image (16).png',
        Link: '/catlist' ,
      },
      {
        id:'28',
        title: 'Photographer',
        img: 'assets\\icon\\category\\image (20).png',
        Link: '/catlist' ,
      },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      // {
      //   id:'',
      //   title: '',
      //   img: '',
      //   Link: '' ,
      // },
      

   ];